# Generated by Django 4.0.2 on 2022-03-17 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(default="", max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("brief", models.TextField(max_length=1000)),
                ("desc", models.TextField(max_length=4000)),
                ("comment", models.TextField(blank=True, max_length=4000, null=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("B", "초급"), ("I", "중급"), ("E", "고급")], max_length=1
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[("S", "15min"), ("L", "30min")], max_length=1
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("", "---------"), ("K", "한글"), ("E", "영어")],
                        default="",
                        max_length=1,
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        help_text="발표 소개 페이지에 들어가는 내용입니다. 변경 사항은 최대 60분 이내에 적용됩니다.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "video_url",
                    models.CharField(
                        blank=True, help_text="발표 영상 URL", max_length=255, null=True
                    ),
                ),
                (
                    "slide_url",
                    models.CharField(
                        blank=True, help_text="발표 자료 URL", max_length=255, null=True
                    ),
                ),
                (
                    "video_open_at",
                    models.DateTimeField(
                        blank=True, help_text="파이콘 한국 유튜브에 공개되는 시간", null=True
                    ),
                ),
                (
                    "track_num",
                    models.IntegerField(blank=True, help_text="트랙 번호", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=14,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="program.programcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
