# Generated by Django 4.0.2 on 2022-03-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="exported",
            field=models.BooleanField(default=False),
        ),
    ]
