# Generated by Django 4.0.2 on 2022-03-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0002_sponsor_exported"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorProxyModel",
            fields=[],
            options={
                "verbose_name": "To Be Send ModuSign",
                "verbose_name_plural": "To Be Send ModuSign",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sponsor.sponsor",),
        ),
    ]
