# Generated by Django 4.0.2 on 2022-09-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0005_sponsor_eng_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalSponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField()),
            ],
            options={
                "ordering": ["amount"],
            },
        ),
    ]
