# Generated by Django 4.0.2 on 2022-05-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="eng_content",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
    ]
